/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function About3D({props, children}) {
  const { nodes, materials } = useGLTF("/Models/Screens/AboutScreen.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[8.168, 2.832, 0.58]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials.PC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials.Screen}
        >
          {children}
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/Screens/AboutScreen.glb");
