/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Contact3D({ props, children }) {
  const { nodes, materials } = useGLTF("/Models/Screens/ContactScreen.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Phone001.geometry}
        material={materials.Screen}
        position={[-0.256, 2.962, -7.322]}
      >
        {children}
      </mesh>
    </group>
  );
}

useGLTF.preload("/Models/Screens/ContactScreen.glb");
