/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useScaleAnimation } from "../../../Animation/useScaleAnimation";

export function Menu3D({ props, children, visible }) {
  const { nodes, materials } = useGLTF("/Models/Screens/MenuScreen.glb");
  const scale = useScaleAnimation(visible, 1, 400);
  return (
    <group {...props} dispose={null} scale={scale}>
      <group position={[1.502, 0.344, 0.157]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials.Screen}
        >
          {children}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials["MetalSilla.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/Screens/MenuScreen.glb");
