/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Menu3D({ props, children, visible }) {
  const { nodes, materials } = useGLTF("/Models/Screens/MenuScreen.glb");
  return (
    <group {...props} dispose={null} visible={visible}>
      <group position={[1.502, 0.344, 0.157]} scale={[0.489, 0.325, 0.429]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials.Screen}
        >
          {children}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials["MetalSilla.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Models/Screens/MenuScreen.glb");
