/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Skills3D({ props, children }) {
  const { nodes, materials } = useGLTF("/Models/Screens/SkillsScreen.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-7.46, 3.935, -2.716]}
        rotation={[Math.PI / 2, 0, -1.171]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials["MetalSilla.001"]}
          scale={[0.8, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.TV_Projects}
          scale={[0.8, 1, 1]}
        />
        <mesh>{children}</mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/Screens/SkillsScreen.glb");
