/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cables({ props, visible = false }) {
  const { nodes, materials } = useGLTF("/Models/Cables.glb");
  return (
    <group {...props} dispose={null} visible={visible}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable2_AboutCopy.geometry}
        material={materials.Cable2Projects}
        position={[-0.152, -0.357, -1.747]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033.geometry}
          material={materials["MetalSilla.001"]}
          position={[-2.832, 0.987, 8.925]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.038, 0.032, 0.038]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable1_AboutCopy.geometry}
        material={materials.Cable1Projects}
        position={[-0.237, 0.32, -1.747]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder032.geometry}
          material={materials["MetalSilla.001"]}
          position={[-2.726, 0.516, 8.925]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.065, 0.054, 0.065]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Models/Cables.glb");
