/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public\Models\Scene.glb 
*/
import Skills from "../Interfaces/Skills/Skills";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useStore from "../../Store/Store";
import * as THREE from "three"; // Importa Three.js

export function Scene3D(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../public/Models/Scene.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  const { showButtonStart } = useStore();
  THREE;
  // // Configuración para que la animación no se repita y se quede en la última posición
  // action.setLoop(THREE.LoopOnce);
  // action.clampWhenFinished = true;

  useEffect(() => {
    console.log(names);
    if (showButtonStart) {
      const sit = actions[names[1]];
      const helmet = actions[names[2]];

      sit.reset().fadeIn(0.5).play();
      sit.time = 2;

      helmet.reset().fadeIn(0.5).play();

      helmet.setLoop(THREE.LoopOnce);
      sit.setLoop(THREE.LoopOnce);
      helmet.clampWhenFinished = true;
      sit.clampWhenFinished = true;
    } else {
      actions[names[0]].reset().fadeIn(0.5).play();
    }
    return () => {
      actions[names[0]].fadeOut(0.5);
    };
  }, [showButtonStart]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Brazo1001">
            <skinnedMesh
              name="Cube008"
              geometry={nodes.Cube008.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube008.skeleton}
            />
            <skinnedMesh
              name="Cube008_1"
              geometry={nodes.Cube008_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube008_1.skeleton}
            />
            <skinnedMesh
              name="Cube008_2"
              geometry={nodes.Cube008_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube008_2.skeleton}
            />
          </group>
          <group name="Brazo2001">
            <skinnedMesh
              name="Cube010"
              geometry={nodes.Cube010.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube010.skeleton}
            />
            <skinnedMesh
              name="Cube010_1"
              geometry={nodes.Cube010_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube010_1.skeleton}
            />
            <skinnedMesh
              name="Cube010_2"
              geometry={nodes.Cube010_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube010_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cabeza001"
            geometry={nodes.Cabeza001.geometry}
            material={materials["Piel.001"]}
            skeleton={nodes.Cabeza001.skeleton}
          />
          <skinnedMesh
            name="Cejas001"
            geometry={nodes.Cejas001.geometry}
            material={materials["Fade2.001"]}
            skeleton={nodes.Cejas001.skeleton}
          />
          <skinnedMesh
            name="Ojos001"
            geometry={nodes.Ojos001.geometry}
            material={materials.Ojos2}
            skeleton={nodes.Ojos001.skeleton}
          />
          <group name="Pelo001">
            <skinnedMesh
              name="Sphere008"
              geometry={nodes.Sphere008.geometry}
              material={materials["Fade1.001"]}
              skeleton={nodes.Sphere008.skeleton}
            />
            <skinnedMesh
              name="Sphere008_1"
              geometry={nodes.Sphere008_1.geometry}
              material={materials["Fade2.001"]}
              skeleton={nodes.Sphere008_1.skeleton}
            />
            <skinnedMesh
              name="Sphere008_2"
              geometry={nodes.Sphere008_2.geometry}
              material={materials["Fade3.001"]}
              skeleton={nodes.Sphere008_2.skeleton}
            />
          </group>
          <group name="Piernas001">
            <skinnedMesh
              name="Cube009"
              geometry={nodes.Cube009.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube009.skeleton}
            />
            <skinnedMesh
              name="Cube009_1"
              geometry={nodes.Cube009_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube009_1.skeleton}
            />
            <skinnedMesh
              name="Cube009_2"
              geometry={nodes.Cube009_2.geometry}
              material={materials["Medias.001"]}
              skeleton={nodes.Cube009_2.skeleton}
            />
          </group>
          <group name="Tenis001">
            <skinnedMesh
              name="Cube011"
              geometry={nodes.Cube011.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube011.skeleton}
            />
            <skinnedMesh
              name="Cube011_1"
              geometry={nodes.Cube011_1.geometry}
              material={materials["Cordones.001"]}
              skeleton={nodes.Cube011_1.skeleton}
            />
            <skinnedMesh
              name="Cube011_2"
              geometry={nodes.Cube011_2.geometry}
              material={materials["TenisBase.001"]}
              skeleton={nodes.Cube011_2.skeleton}
            />
            <skinnedMesh
              name="Cube011_3"
              geometry={nodes.Cube011_3.geometry}
              material={materials["Tenis2.001"]}
              skeleton={nodes.Cube011_3.skeleton}
            />
            <skinnedMesh
              name="Cube011_4"
              geometry={nodes.Cube011_4.geometry}
              material={materials["Tenis3.001"]}
              skeleton={nodes.Cube011_4.skeleton}
            />
          </group>
          <group name="Torzo2">
            <skinnedMesh
              name="Cube012"
              geometry={nodes.Cube012.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube012.skeleton}
            />
            <skinnedMesh
              name="Cube012_1"
              geometry={nodes.Cube012_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube012_1.skeleton}
            />
          </group>
        </group>
        <mesh
          name="Silla"
          geometry={nodes.Silla.geometry}
          material={materials.Silla2}
          position={[0, 0.344, -0.009]}
          scale={[0.758, 0.751, 0.489]}
        >
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={materials.MetalSilla}
            position={[0, -0.088, -0.065]}
            scale={[0.468, 0.606, 0.931]}
          />
          <group
            name="Plane002"
            position={[0.002, 1.261, -1.161]}
            rotation={[1.485, 0, 0]}
            scale={[1.058, 0.921, 0.864]}
          >
            <mesh
              name="Mesh_1"
              geometry={nodes.Mesh_1.geometry}
              material={materials.Silla2}
            />
            <mesh
              name="Mesh_2"
              geometry={nodes.Mesh_2.geometry}
              material={materials.Silla1}
            />
            <mesh
              name="Almohada"
              geometry={nodes.Almohada.geometry}
              material={materials.Silla2}
              position={[0, -0.145, -0.543]}
              rotation={[-1.468, 0, 0]}
              scale={[0.669, 0.203, 0.353]}
            />
            <mesh
              name="SoporteCasco"
              geometry={nodes.SoporteCasco.geometry}
              material={materials.Casco1}
              position={[0.015, 1.367, -1.346]}
              rotation={[-1.403, 0, 0]}
              scale={[0.862, 1.082, 1.522]}
            >
              <mesh
                name="CilindroCasco"
                geometry={nodes.CilindroCasco.geometry}
                material={nodes.CilindroCasco.material}
                position={[0, -0.161, -0.909]}
                rotation={[-1.391, 0, -Math.PI / 2]}
                scale={[0.102, 0.409, 0.102]}
              >
                <group
                  name="Sphere"
                  position={[-1.6, 0, 8.932]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[2.448, 9.774, 9.774]}
                >
                  <mesh
                    name="Sphere006"
                    geometry={nodes.Sphere006.geometry}
                    material={materials.Casco1}
                  />
                  <mesh
                    name="Sphere006_1"
                    geometry={nodes.Sphere006_1.geometry}
                    material={materials.Casco2}
                  />
                </group>
              </mesh>
            </mesh>
          </group>
          <group
            name="Silla002"
            position={[-0.993, 0.308, 0]}
            scale={[0.136, 1, 1]}
          >
            <mesh
              name="Plane011"
              geometry={nodes.Plane011.geometry}
              material={materials.Silla2}
            />
            <mesh
              name="Plane011_1"
              geometry={nodes.Plane011_1.geometry}
              material={materials.Silla1}
            />
          </group>
        </mesh>
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={nodes.Floor.material}
          position={[0, -0.989, 0]}
          scale={[22.003, 1, 22.003]}
        />
        <group
          name="CableTecho1"
          position={[0.014, 5.13, -0.134]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.658}
        >
          <mesh
            name="BezierCurve"
            geometry={nodes.BezierCurve.geometry}
            material={materials.Tubo1}
          />
          <mesh
            name="BezierCurve_1"
            geometry={nodes.BezierCurve_1.geometry}
            material={materials.Tubo2}
          />
        </group>
        <mesh
          name="About"
          geometry={nodes.About.geometry}
          material={nodes.About.material}
          position={[-8.326, 1.802, -8.197]}
          scale={1.821}
        />
        <mesh
          name="Contact"
          geometry={nodes.Contact.geometry}
          material={nodes.Contact.material}
          position={[5.79, 1.802, -10.668]}
          scale={1.821}
        ></mesh>
        <mesh
          name="Projects"
          geometry={nodes.Projects.geometry}
          material={nodes.Projects.material}
          position={[11.153, 1.802, 3.015]}
          scale={1.821}
        />
        <group
          name="Skills"
          position={[-9.158, 1.09, 6.052]}
          rotation={[-Math.PI, 1.004, -Math.PI]}
          scale={1.106}
        >
          <mesh
            name="Cube018"
            geometry={nodes.Cube018.geometry}
            material={materials.SkillsBase}
          />
          <mesh
            name="Cube018_1"
            geometry={nodes.Cube018_1.geometry}
            material={materials.SkillsBase2}
          />
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={nodes.Cube006.material}
            position={[-0.493, 1.38, -0.453]}
            scale={[0.116, 0.155, 0.026]}
          />
          <group name="Cube007" position={[0, 2.251, -0.449]} scale={1.104}>
            <mesh
              name="Cube020"
              geometry={nodes.Cube020.geometry}
              material={materials.SkillsBase}
            />
            <mesh
              name="Cube020_1"
              geometry={nodes.Cube020_1.geometry}
              material={materials.SkillsBase2}
            >
              {/* {!props.showFloatButtons && <Skills />} */}
              <Skills></Skills>
            </mesh>
          </group>
        </group>
        <mesh
          name="Cable2"
          geometry={nodes.Cable2.geometry}
          material={nodes.Cable2.material}
          position={[-6.898, 0.066, 4.316]}
        />
        <mesh
          name="Cable1"
          geometry={nodes.Cable1.geometry}
          material={nodes.Cable1.material}
          position={[-6.843, 0.066, 4.481]}
        />
        <mesh
          name="Menu"
          geometry={nodes.Menu.geometry}
          material={nodes.Menu.material}
          position={[1.331, 0.344, -0.009]}
          scale={0.325}
        />
        <group
          name="CableTecho2"
          position={[-0.029, 5.13, -0.117]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.658}
        >
          <mesh
            name="BezierCurve001_1"
            geometry={nodes.BezierCurve001_1.geometry}
            material={materials.Tubo1}
          />
          <mesh
            name="BezierCurve001_2"
            geometry={nodes.BezierCurve001_2.geometry}
            material={materials.Tubo2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../public/Models/Scene.glb");
