/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Models/Character.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../public/Models/Character.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    console.log(names);
    const action = actions[names[1]];
    action.reset().fadeIn(0.5).play();

    // Configuración para que la animación no se repita y se quede en la última posición
    action.setLoop(THREE.LoopOnce);
    action.clampWhenFinished = true;
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="Brazo1001">
            <skinnedMesh
              name="Cube008"
              geometry={nodes.Cube008.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube008.skeleton}
            />
            <skinnedMesh
              name="Cube008_1"
              geometry={nodes.Cube008_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube008_1.skeleton}
            />
            <skinnedMesh
              name="Cube008_2"
              geometry={nodes.Cube008_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube008_2.skeleton}
            />
          </group>
          <group name="Brazo2001">
            <skinnedMesh
              name="Cube010"
              geometry={nodes.Cube010.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube010.skeleton}
            />
            <skinnedMesh
              name="Cube010_1"
              geometry={nodes.Cube010_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube010_1.skeleton}
            />
            <skinnedMesh
              name="Cube010_2"
              geometry={nodes.Cube010_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube010_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cabeza001"
            geometry={nodes.Cabeza001.geometry}
            material={materials["Piel.001"]}
            skeleton={nodes.Cabeza001.skeleton}
          />
          <skinnedMesh
            name="Cejas001"
            geometry={nodes.Cejas001.geometry}
            material={materials["Fade2.001"]}
            skeleton={nodes.Cejas001.skeleton}
          />
          <skinnedMesh
            name="Ojos001"
            geometry={nodes.Ojos001.geometry}
            material={materials["Fade2.001"]}
            skeleton={nodes.Ojos001.skeleton}
          />
          <group name="Pelo001">
            <skinnedMesh
              name="Sphere008"
              geometry={nodes.Sphere008.geometry}
              material={materials["Fade1.001"]}
              skeleton={nodes.Sphere008.skeleton}
            />
            <skinnedMesh
              name="Sphere008_1"
              geometry={nodes.Sphere008_1.geometry}
              material={materials["Fade2.001"]}
              skeleton={nodes.Sphere008_1.skeleton}
            />
            <skinnedMesh
              name="Sphere008_2"
              geometry={nodes.Sphere008_2.geometry}
              material={materials["Fade3.001"]}
              skeleton={nodes.Sphere008_2.skeleton}
            />
          </group>
          <group name="Piernas001">
            <skinnedMesh
              name="Cube009"
              geometry={nodes.Cube009.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube009.skeleton}
            />
            <skinnedMesh
              name="Cube009_1"
              geometry={nodes.Cube009_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube009_1.skeleton}
            />
            <skinnedMesh
              name="Cube009_2"
              geometry={nodes.Cube009_2.geometry}
              material={materials["Medias.001"]}
              skeleton={nodes.Cube009_2.skeleton}
            />
          </group>
          <group name="Tenis001">
            <skinnedMesh
              name="Cube011"
              geometry={nodes.Cube011.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube011.skeleton}
            />
            <skinnedMesh
              name="Cube011_1"
              geometry={nodes.Cube011_1.geometry}
              material={materials["Cordones.001"]}
              skeleton={nodes.Cube011_1.skeleton}
            />
            <skinnedMesh
              name="Cube011_2"
              geometry={nodes.Cube011_2.geometry}
              material={materials["TenisBase.001"]}
              skeleton={nodes.Cube011_2.skeleton}
            />
            <skinnedMesh
              name="Cube011_3"
              geometry={nodes.Cube011_3.geometry}
              material={materials["Tenis2.001"]}
              skeleton={nodes.Cube011_3.skeleton}
            />
            <skinnedMesh
              name="Cube011_4"
              geometry={nodes.Cube011_4.geometry}
              material={materials["Tenis3.001"]}
              skeleton={nodes.Cube011_4.skeleton}
            />
          </group>
          <group name="Torzo2">
            <skinnedMesh
              name="Cube012"
              geometry={nodes.Cube012.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube012.skeleton}
            />
            <skinnedMesh
              name="Cube012_1"
              geometry={nodes.Cube012_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube012_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../public/Models/Character.glb");
