/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/IronManAnim.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function IronManAnim(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./Models/IronManAnim.glb");
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            castShadow
            name="IronManModel001"
            geometry={nodes.IronManModel001.geometry}
            material={materials["Iron_Man1.002"]}
            skeleton={nodes.IronManModel001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./Models/IronManAnim.glb");
